# Use new container infrastructure to enable caching
sudo: false
language: nix

# Caching so the next build will be fast too.
cache:
  directories:
  - /nix/store

# The different configurations we want to test. We have BUILD=cabal which uses
# cabal-install, and BUILD=stack which uses Stack. More documentation on each
# of those below.
#
# We set the compiler values here to tell Travis to use a different
# cache file per set of arguments.
#
# If you need to have different apt packages for each combination in the
# matrix, you can use a line such as:
#     addons: {apt: {packages: [libfcgi-dev,libgmp-dev]}}
matrix:
  include:
  # OSX Build High Sierra
  - env: BUILD=nix ARGS=""
    compiler: "nix osx default (high sierra)"
    os: osx
    osx_image: xcode9.3
    addons:
      artifacts:
        paths:
          - result/ghc/pact-server/bin/pact

  # Linux build
  - env: BUILD=nix ARGS=""
    compiler: "nix default linux"
    addons:
      artifacts:
        paths:
          - result/ghc/pact-server/bin/pact



  # OSX Build Yosemite
  # - env: BUILD=stack ARGS=""
  #   compiler: ": #stack default osx (yosemite)"
  #   os: osx
  #   osx_image: xcode7.1
  #   addons:
  #     artifacts:
  #       paths:
  #         - .stack-work/dist/x86_64-osx/Cabal-1.22.5.0/build/Pact/pact

  allow_failures: []
  # - env: BUILD=cabal GHCVER=head  CABALVER=head HAPPYVER=1.19.5 ALEXVER=3.1.7
  # - env: BUILD=stack ARGS="--resolver nightly"

before_install:
# Using compiler above sets CC to an invalid value, so unset it
- unset CC
# https://github.com/travis-ci/travis-ci/issues/6307
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; command curl -sSL https://rvm.io/mpapis.asc | gpg --import -; then rvm get stable; fi
- echo $NIX_CONF_DIR
- echo "substituters = http://18.188.255.165 https://nixcache.reflex-frp.org https://cache.nixos.org/" >> $HOME/nix.conf
- echo "trusted-public-keys = ryantrinkle.com-1:JJiAKaRv9mWgpVAz8dwewnZe0AzzEAzPkagE9SP5NWI= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=" >> $HOME/nix.conf
- cat $HOME/nix.conf

install:
- uname -a
- nix-build --version
- if [ -f configure.ac ]; then autoreconf -i; fi
- |
  set -ex
  NIX_CONF_DIR=$HOME nix-build
  set +ex

script:
- |
  set -ex
  curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s .
  curl -sL https://raw.github.com/ndmitchell/weeder/master/misc/travis.sh | sh -s .
  result/ghc/pact-server/bin/bench +RTS -K1k
  set +ex
