# stack yaml for ghc builds

resolver: lts-8.15

packages:
- '.'
- location:
    git: https://github.com/slpopejoy/snap-cors.git
    commit: cc88bab1fd3f62dc4d9f9ad81a231877a639c812
  extra-dep: true
- location:
    git: https://github.com/kadena-io/thyme.git
    commit: 6ee9fcb026ebdb49b810802a981d166680d867c9
  extra-dep: true
- location:
    git: https://github.com/LeventErkok/sbv.git
    commit: dbbdd396d069dc8235f5c8cf58209886318f6525 # with symbolic string support
  extra-dep: true

extra-deps:
  - bound-2
  - ed25519-donna-0.1.1
  - hashable-1.2.6.1
  - easytest-0.2
  - containers-0.5.8.2
  - hlint-2.1.5
  - extra-1.6.6
  - aeson-1.1.2.0
  - haskell-src-exts-1.20.2
  - haskell-src-exts-util-0.2.3
flags: {}

extra-package-dbs: []
