# stack yaml for ghc builds

resolver: lts-6.12

packages:
- '.'
- location:
    git: git@bitbucket.org:spopejoy/pact.git
    commit: c6d1d799baaf1d93353f753eb78fc1c73cc26920
  extra-dep: true
- location:
    git: git@github.com:buckie/Hsmtlib.git
    commit: 1fec7492100c0ff72bdb87ffc841eabfdce2a27f
  extra-dep: true
- location:
    git: git@github.com:buckie/SmtLib.git
    commit: d19457c665aed402ff7069712cac12f4c433c6d6
  extra-dep: true

extra-deps:
- trifecta-1.6
- show-prettyprint-0.1.2

flags: {}

extra-package-dbs: []
