# stack yaml for ghc builds

resolver: lts-8.15

packages:
- '.'
- location:
    git: https://github.com/slpopejoy/snap-cors.git
    commit: cc88bab1fd3f62dc4d9f9ad81a231877a639c812
  extra-dep: true

extra-deps:
  - bound-2
  - ed25519-donna-0.1.1
  - hashable-1.2.6.1
flags: {}

extra-package-dbs: []
