# stack yaml for ghc builds

resolver: lts-6.12

packages:
- '.'
- location:
    git: git@bitbucket.org:spopejoy/pact.git
    commit: 36854a3b62df954deee39a90fc591e3faf4618c4
  extra-dep: true
- location:
    git: git@github.com:buckie/Hsmtlib.git
    commit: 1fec7492100c0ff72bdb87ffc841eabfdce2a27f
  extra-dep: true
- location:
    git: git@github.com:buckie/SmtLib.git
    commit: d954aaf13e0418dfc354828ab1db0afdff212fd7
  extra-dep: true

extra-deps:
- trifecta-1.6
- show-prettyprint-0.1.2

flags: {}

extra-package-dbs: []
