# stack yaml for ghc builds

resolver: lts-8.15

packages:
- '.'
- location:
    git: https://github.com/slpopejoy/snap-cors.git
    commit: cc88bab1fd3f62dc4d9f9ad81a231877a639c812
  extra-dep: true
- location:
    git: https://github.com/kadena-io/thyme.git
    commit: 6ee9fcb026ebdb49b810802a981d166680d867c9
  extra-dep: true
- location:
    git: https://github.com/bts/sbv.git
    commit: 8abfc6ead4ee42d331265544cb6acc508249776f # with exposed SMTValue methods
  extra-dep: true

extra-deps:
  - bound-2
  - ed25519-donna-0.1.1
  - hashable-1.2.6.1
  - containers-0.5.8.2
  - monad-gen-0.3.0.1

flags: {}

extra-package-dbs: []
