# stack yaml for ghc builds

resolver: lts-8.15

packages:
- '.'
- location:
    # On a branch until https://github.com/kadena-io/pact/pull/50 is merged
    git: git@github.com:kadena-io/pact.git
    commit: 3dbbf09ff8d09ec7f0e271146e1e66c4a3fae1f0
  extra-dep: true
- location:
    git: git@github.com:buckie/Hsmtlib.git
    commit: f39f51be1c0793646f1a5a1eae1160c37dddfb57
  extra-dep: true
- location:
    git: git@github.com:buckie/SmtLib.git
    commit: 76f78603a84175e70c55a5de59fab7733337119b
  extra-dep: true
- location:
    git: https://github.com/kadena-io/thyme.git
    commit: 6ee9fcb026ebdb49b810802a981d166680d867c9
  extra-dep: true
- location:
    git: https://github.com/LeventErkok/sbv.git
    commit: 55d4288c9a088852625a69d49644beb85446ec1c # symbolic_strings branch
  extra-dep: true

extra-deps:
  - bound-2.0.1
  - ed25519-donna-0.1.1
  - easytest-0.2

flags: {}

extra-package-dbs: []
