# stack yaml for ghc builds

resolver: lts-6.12

packages:
- '.'
- location:
    git: https://github.com/slpopejoy/snap-cors.git
    commit: cc88bab1fd3f62dc4d9f9ad81a231877a639c812
  extra-dep: true

extra-deps:
- trifecta-1.6
- ed25519-donna-0.1.1
- safe-exceptions-0.1.4.0

flags: {}

extra-package-dbs: []
