# stack yaml for ghc builds

resolver: lts-6.12

packages:
- '.'
- location:
    git: git@bitbucket.org:spopejoy/pact.git
    commit: 7e258898f9688084582713ca47fa341ecf2324be

extra-deps:
- trifecta-1.6

flags: {}

extra-package-dbs: []
